USE [gann]
GO

/****** Object:  Table [dbo].[flow_data]    Script Date: 24/10/2020 21:07:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[flow_data](
	[idx] [bigint] NULL,
	[dst_port] [bigint] NULL,
	[protocol] [bigint] NULL,
	[timestamp] [datetime] NULL,
	[flow_duration] [bigint] NULL,
	[tot_fwd_pkts] [bigint] NULL,
	[tot_bwd_pkts] [bigint] NULL,
	[totlen_fwd_pkts] [bigint] NULL,
	[totlen_bwd_pkts] [bigint] NULL,
	[fwd_pkt_len_max] [bigint] NULL,
	[fwd_pkt_len_min] [bigint] NULL,
	[fwd_pkt_len_mean] [float] NULL,
	[fwd_pkt_len_std] [float] NULL,
	[bwd_pkt_len_max] [bigint] NULL,
	[bwd_pkt_len_min] [bigint] NULL,
	[bwd_pkt_len_mean] [float] NULL,
	[bwd_pkt_len_std] [float] NULL,
	[flow_byts/s] [float] NULL,
	[flow_pkts/s] [float] NULL,
	[flow_iat_mean] [float] NULL,
	[flow_iat_std] [float] NULL,
	[flow_iat_max] [bigint] NULL,
	[flow_iat_min] [bigint] NULL,
	[fwd_iat_tot] [bigint] NULL,
	[fwd_iat_mean] [float] NULL,
	[fwd_iat_std] [float] NULL,
	[fwd_iat_max] [bigint] NULL,
	[fwd_iat_min] [bigint] NULL,
	[bwd_iat_tot] [bigint] NULL,
	[bwd_iat_mean] [float] NULL,
	[bwd_iat_std] [float] NULL,
	[bwd_iat_max] [bigint] NULL,
	[bwd_iat_min] [bigint] NULL,
	[fwd_psh_flags] [bigint] NULL,
	[bwd_psh_flags] [bigint] NULL,
	[fwd_urg_flags] [bigint] NULL,
	[bwd_urg_flags] [bigint] NULL,
	[fwd_header_len] [bigint] NULL,
	[bwd_header_len] [bigint] NULL,
	[fwd_pkts/s] [float] NULL,
	[bwd_pkts/s] [float] NULL,
	[pkt_len_min] [bigint] NULL,
	[pkt_len_max] [bigint] NULL,
	[pkt_len_mean] [float] NULL,
	[pkt_len_std] [float] NULL,
	[pkt_len_var] [float] NULL,
	[fin_flag_cnt] [bigint] NULL,
	[syn_flag_cnt] [bigint] NULL,
	[rst_flag_cnt] [bigint] NULL,
	[psh_flag_cnt] [bigint] NULL,
	[ack_flag_cnt] [bigint] NULL,
	[urg_flag_cnt] [bigint] NULL,
	[cwe_flag_count] [bigint] NULL,
	[ece_flag_cnt] [bigint] NULL,
	[down/up_ratio] [bigint] NULL,
	[pkt_size_avg] [float] NULL,
	[fwd_seg_size_avg] [float] NULL,
	[bwd_seg_size_avg] [float] NULL,
	[fwd_byts/b_avg] [bigint] NULL,
	[fwd_pkts/b_avg] [bigint] NULL,
	[fwd_blk_rate_avg] [bigint] NULL,
	[bwd_byts/b_avg] [bigint] NULL,
	[bwd_pkts/b_avg] [bigint] NULL,
	[bwd_blk_rate_avg] [bigint] NULL,
	[subflow_fwd_pkts] [bigint] NULL,
	[subflow_fwd_byts] [bigint] NULL,
	[subflow_bwd_pkts] [bigint] NULL,
	[subflow_bwd_byts] [bigint] NULL,
	[init_fwd_win_byts] [bigint] NULL,
	[init_bwd_win_byts] [bigint] NULL,
	[fwd_act_data_pkts] [bigint] NULL,
	[fwd_seg_size_min] [bigint] NULL,
	[active_mean] [float] NULL,
	[active_std] [float] NULL,
	[active_max] [bigint] NULL,
	[active_min] [bigint] NULL,
	[idle_mean] [float] NULL,
	[idle_std] [float] NULL,
	[idle_max] [bigint] NULL,
	[idle_min] [bigint] NULL,
	[label] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


